In [1]:
import pandas as pd
import MeCab
from gensim import models

df = pd.read_csv("../data/tweets.csv")
mecab = MeCab.Tagger ("-Owakati")
print(mecab.parse("pythonが大好きです"))

df = df[pd.isnull(df.retweeted_status_id)]
df = df[pd.isnull(df.in_reply_to_status_id)]

for index, row in df.iterrows():
    if not pd.isnull(row.text):
        df.set_value(index, "text", mecab.parse(row["text"]))        
        
for index, row in df.iterrows():
    if not pd.isnull(row.text):
        print(row.text)
    if index > 10 : break;

python が 大好き です 

無理 だ ー 

人間 よ 、 24 に 、 分類 さ れよ ！ 

計算 中 ・ ・ ・ 

えい 、 ` from scipy . cluster . vq import vq , kmeans , whiten ` 

k - means やる ぞ 

17 件 の コメント https :// t . co / 4 wBdeSUFov “ Rails エンジニア に 役立つ Jupyter Notebook と iRuby - クック パッド 開発 者 ブログ ” https :// t . co / gn 3 VupaJH 1 

1 時間 で 配送 できる 理由 が わから ん https :// t . co / 9 q 6 R 0 jnR 4 D 

お は よー ！ 6 h 28 m ね た よ ！ January 27 , 2016 at 01 : 19 AM → January 27 , 2016 at 08 : 06 AM 

これ は 楽しみ すぎる やろ / “ パーフェクト ボディ を 目指し て ( １ 日 経過 ） - alwaysneet な 毎日 ” https :// t . co / ounxQFuw 7 W 

ねむい ー 

" Microsoft が 機械 学習 ツール キット CNTK を GitHub に 移し MIT ライセンス を 適用 " # tech # feedly https :// t . co / G 8 iqMk 5 q 44 



In [2]:
df.to_csv("../data/formatted_tweets.csv")

In [3]:
import itertools
class LabeledLineSentence(object):
    def __init__(self, df):
        self.df = df

    def __iter__(self):
        for index, row in self.df.iterrows():            
            yield models.doc2vec.LabeledSentence(row["text"].split(), ['text_%s' % index])
            

sentence = LabeledLineSentence(df)
print(list(sentence)[:5])
len(df)

[LabeledSentence(words=['無理', 'だ', 'ー'], tags=['text_1']), LabeledSentence(words=['人間', 'よ', '、', '24', 'に', '、', '分類', 'さ', 'れよ', '！'], tags=['text_2']), LabeledSentence(words=['計算', '中', '・', '・', '・'], tags=['text_3']), LabeledSentence(words=['えい', '、', '`', 'from', 'scipy', '.', 'cluster', '.', 'vq', 'import', 'vq', ',', 'kmeans', ',', 'whiten', '`'], tags=['text_4']), LabeledSentence(words=['k', '-', 'means', 'やる', 'ぞ'], tags=['text_5'])]


16435

In [4]:
from gensim import models
model = models.Doc2Vec()
model.build_vocab(sentence)

for _ in range(10):
    model.train(sentence)
    print("トレーニング" + str(_) + "終了")

トレーニング0終了
トレーニング1終了
トレーニング2終了
トレーニング3終了
トレーニング4終了
トレーニング5終了
トレーニング6終了
トレーニング7終了
トレーニング8終了
トレーニング9終了


In [26]:
# model.vocab.keys()

In [5]:
model.most_similar("リクルート")

[('さくら', 0.4697413146495819),
 ('グレー', 0.4638863205909729),
 ('クリエイター', 0.44836190342903137),
 ('法則', 0.42502859234809875),
 ('アマゾン', 0.4250173270702362),
 ('Backlog', 0.42153939604759216),
 ('特集', 0.4198557734489441),
 ('サイバーエージェント', 0.4193626046180725),
 ('株式会社', 0.41841578483581543),
 ('TestFlight', 0.41819602251052856)]

In [6]:
base = "text_1"
key, index = base.split("_")
print(df.ix[int(index)][key])
for offset, similality in model.docvecs.most_similar(base):
    doctag = model.docvecs.offset2doctag[offset]
    key, index = doctag.split("_")
    print("%s%%"%int(similality*100),df.ix[int(index)][key])

無理 だ ー 

71% 無料 で 遊ん だ ー 

64% 徐々に 英語 に なっ て いく ぜ ー 

63% wercker 便利 だ 。 無料 だ 。 

62% なんと ！ cRT @ yoichineji : cocos 2 d - html 5 v 2 . 0 が リリース さ れ た よう だ ー 

61% だ ー ぱん の リバー シ だ 。 こういう キャラ 戦略 よい なぁ 。 / “ Connecting to the iTunes Store .” http :// t . co / 6 l 7 VAkr 9 Jd 

61% 稼ぐ ぞ ー 。 

59% アドビ 製品 ほしい ！ と 思っ たら 高 すぎ だろ ． あぁ ー で も みんな あれ だけ 買っ てる って こと は それ だけ いい 商品 な ん だろ う なー ． いや ， そんな お金 ない ！ 

59% ビール 部 自主トレ だ と ー ！ 

58% 難しい です 

57% イカ 電話 だ よ https :// t . co / gG 38 UfpUEt 



In [7]:
from scipy.cluster.vq import vq, kmeans, whiten
centroid, destortion = kmeans(model.docvecs, 10 , iter=100, thresh=1e-05)

In [8]:
labels, dist = vq(model.docvecs, centroid)
print(labels[:5]) # どのクラスターに入ってるか
print(dist[:5]) # 中心からの距離

[4 9 6 8 7]
[ 0.46845675  0.45421341  0.26098078  0.51132739  0.38723773]


In [9]:
df = pd.read_csv("../data/tweets.csv")
for label in range(10):
    print(label,"スタート")
    print_i = 0
    for i in range(model.docvecs.count):
        if labels[i] == label:
            dist_vec = vq([model.docvecs[i]], centroid)
            doctag = model.docvecs.offset2doctag[i]
            key, index = doctag.split("_")
            if int((1.-dist[i])*100) > 70 and not pd.isnull(df.ix[int(index)][key]):
#                 print(dist_vec)
                print("%s%%"%int((1.-dist[i])*100),df.ix[int(index)][key].strip("\t\n"))
                print_i +=1
                if print_i > 3 : 
                    print("\n");break;

0 スタート
72% あぁ、またフェス行きたい
71% タイガーナッツ気になる
71% なにこれ
72% おはよー！ 7h 6m ねたよ！ December 28, 2015 at 02:01AM →December 28, 2015 at 09:16AM


1 スタート
74% 体力を付ける方法を熱望している
71% アーロンチェア最高や
73% AppleTVほしいけど、スタバでモテない
71% 数学者が解説するコンピューターサイエンスの本とかないかな


2 スタート
71% 届いたよ！ http://t.co/xBFgoTbVu5
76% http://t.co/W5K79n0Hov
73% ブートキャンプに飛び入ることになった
74% C++で多倍長整数扱うにはどうしたらいいのか


3 スタート
72% 英語を高速で読めるようになりたい
71% 2件のコメント https://t.co/XGPnQucm7V “実例で学ぶDockerハンズオン - Qiita” https://t.co/PLxuMASLGE
79% “溶解度 - Wikipedia” https://t.co/leHn71kEWo
72% これは / “SimPholders2” https://t.co/xwvCJiyUf2


4 スタート
72% togglで時間管理していきたい
72% 脳を動かすのは難しい
74% すげー / “風邪 - Wikipedia” https://t.co/nQY4DaKsV6
79% アレクサンダー ステパノフ の プログラミング言論 を Amazon でチェック！ http://t.co/XlZ0nGpbXW @さんから


5 スタート
71% ZeroPush › Transactional Push Notifications for Developers https://t.co/fjfB2QhhqI
72% http://t.co/WAuMJpEjujで登録しても日本の広告出るんやろうか
71% Haskel RT @lotz84_: Ocaml https://t.co/8s66iPbdej
72% pyenvにPR投げてマージされました


6 スタート
73% 計算中・・・
76% ジョコビッチ https://t.co/h3x

In [33]:
import numpy as np
sim_matrix = []
size = model.docvecs.count
for i in range(model.docvecs.count):
    sim_vec = np.zeros(size)
    for word_index, sim_val in model.docvecs.most_similar(i):
        sim_vec[word_index] = sim_val
    sim_matrix.append(sim_vec)

In [34]:
from sklearn.decomposition import TruncatedSVD
dimension = 100
lsa = TruncatedSVD(dimension)
info_matrix = lsa.fit_transform(sim_matrix)

In [35]:
centroid, destortion = kmeans(info_matrix, 10 , iter=100, thresh=1e-05)

In [36]:
labels, dist = vq(info_matrix, centroid)
print(labels[:5]) # どのクラスターに入ってるか
print(dist[:5]) # 中心からの距離

[3 3 3 3 3]
[ 0.3263844   0.98892408  0.23776124  0.30133668  0.10600836]


In [43]:
df = pd.read_csv("../data/tweets.csv")
for label in range(10):
    print(label,"スタート")
    print_i = 0
    for i in range(model.docvecs.count):
        if labels[i] == label:
            doctag = model.docvecs.offset2doctag[i]
            key, index = doctag.split("_")
            if int((1.-dist[i])*100) > 40 and not pd.isnull(df.ix[int(index)][key]):
#                 print(dist_vec)
                print("%s%%「"%int((1.-dist[i])*100),df.ix[int(index)][key].strip("\t\n"),"」")
                print_i +=1
                if print_i > 3 : break;
    print("\n");

0 スタート
42%「 おはよー！ 1h 3m ねたよ！ January 11, 2016 at 10:34AM →January 11, 2016 at 11:38AM 」
41%「 おはよー！ 7h 46m ねたよ！ November 16, 2015 at 12:22AM →November 16, 2015 at 08:40AM 」
59%「 おはよー！ 1h 18m ねたよ！ November 8, 2015 at 08:57AM →November 8, 2015 at 10:17AM 」
49%「 おはよー！ 7h 55m ねたよ！ November 8, 2015 at 12:35AM →November 8, 2015 at 08:56AM 」


1 スタート
57%「 テンソルフロー！ 」
76%「 カエル頑張れ！ 」
45%「 @iphone_dev_jp 【拡散希望】IQ診断という新作アプリをリリースしました！100ステージの大ボリュームでIQが診断できます！

よろしくお願いします！

https://t.co/Pgx2qLp2xN https://t.co/ydzvzMujFe 」
63%「 そういえば、今使ってるMBPがNVIDIAなので、GPU使えるじゃん！！ 」


2 スタート
47%「 家の光の改善について
明るすぎ！？睡眠の質を高めるために、光について考えよう - kasajeiのブログ
https://t.co/4bV6uZ1fns https://t.co/29WRgMTG0u 」
45%「 これかな / “ギー（インドAmul社）1L. 通販・販売 - マヤバザール” https://t.co/ZEWTzqasoQ 」
47%「 新しいコールハーンを手に入れたので前の修理に出そう 」
46%「 睡眠時間は6.5h以上はあんまり意味ないらしいので、6.5hで最適化していきたい 」


3 スタート
67%「 無理だー 」
76%「 計算中・・・ 」
69%「 えい、 `from scipy.cluster.vq import vq, kmeans, whiten` 」
89%「 k-meansやるぞ 」


4 スタート
58%「 あぁ、えーっと。60倍多かった。

で、7円/月。

ロングポーリング使わないと、140円